### ISSUE TITLE
referenced 'marklar' color scheme not included

### ISSUE THREAD

**Issue by spazm** [ceocoder/dotfiles#1]
'marklar' color scheme is referenced in vimrc, line 124.  This color scheme is not installed during the bootstrap phase.

```
124 colorscheme marklar                                                                                                   
```

Have you installed from [vim-script 1483](http://www.vim.org/scripts/script.php?script_id=1483), from [github vim-scripts](https://github.com/vim-scripts/marklar.vim), rpm `vim-plugin-colorschemes-1.0-30.2.noarch` or from somewhere else?

**Comment by ceocoder** [comment]
@spazm that colorscheme gets installed during vim bootstrap phase (`vim +BundleInstall`) from `vim-colorscheme` plugin at https://github.com/ceocoder/dotfiles/blob/master/vimrc#L59 -

**Comment by ceocoder** [comment]
source https://github.com/flazz/vim-colorschemes/blob/master/colors/marklar.vim
